#!/bin/bash
# Clint Aegerter
# Uses plot_real_time_wrf NCL scripts to plot .png images.
# Syntax: ncl plot_real_time_wrf_*.ncl dir=\"directory\" filelist =\"filelist"\

module load WRF

date +"%T"

# Set run time of model
run="14033106"
#directory='/work/jwang7/caegerter/test/'$run'/wrfout/'
directory="/work/swanson/jingchao/wrf/data/wrf_chem/20140331/14033106/"

# Create list of WRF output files
ls wrfout* | xargs -n1 basename > $run'_list'
flist='"'$run'_list"'

# Create directories for images
rm -rf images
mkdir $directory'images'
mkdir $directory'images/dewpoint'
mkdir $directory'images/temp'
mkdir $directory'images/upper_air'
mkdir $directory'images/precip'
mkdir $directory'images/reflectivity'

# Modify directory so it is passed correctly to NCL scripts
directory='"'$directory'"'

# Run NCL scripts
echo "Working on 2m temperature plots ==============================="
ncl plot_real_time_wrf_2mtemp.ncl dir=$directory filelist=$flist

echo "Working on 2m dewpoint plots =================================="
ncl plot_real_time_wrf_2mdewpoint.ncl dir=$directory filelist=$flist

echo "Working on 3hr precipitation plots ============================"
ncl plot_real_time_wrf_3hrprecip.ncl dir=$directory filelist=$flist

echo "Working on reflectivity plots ================================="
ncl plot_real_time_wrf_reflectivity.ncl dir=$directory filelist=$flist

echo "Working on upper air plots ===================================="
ncl plot_real_time_wrf_upperair.ncl dir=$directory filelist=$flist

date +"%T"
